### ISSUE TITLE
Nested ICs causes issues

### ISSUE THREAD

**Issue by Bobingstern** [UnsignedArduino/LogicalSimulator#175]
**Describe the bug**
When creating a full adder, i first created an IC for the half adder which works perfectly without any problems. Afterwards, to create a full-adder, I use 2 separate half-adders and this causes an exception when trying to "Get IC"

**To Reproduce**
Create this circuit below and select the full adder ic and press the "get ic" button and try to place. You will get an exception. The following JSON export code is for the circuit: `{"version":0,"components":[{"id":"component12","type":16,"x":-39.97892560073534,"y":-27.913789332655774,"angle":0,"icName":"half-adder","icPins":"{\n  \"top\": \"\",\n  \"right\": \"output,output\",\n  \"bottom\": \"\",\n  \"left\": \"input,input\"\n}"},{"id":"component14","type":13,"x":-34.73924958079069,"y":-92.23645737772985,"angle":0},{"id":"component16","type":11,"x":-36.88333851562649,"y":25.926666142109937,"angle":0},{"id":"component37","type":16,"x":196.93747330363104,"y":-167.79679664806494,"angle":0,"icName":"full-adder","icPins":"{\n  \"top\": \"\",\n  \"right\": \"output,output\",\n  \"bottom\": \"\",\n  \"left\": \"input,input,input\"\n}"},{"id":"component41","type":17,"x":204.1995401797366,"y":-59.07441053966554,"angle":0,"icDefID":"component12"},{"id":"component47","type":17,"x":335.27984729344246,"y":-96.47405495160913,"angle":0,"icDefID":"component12"},{"id":"component51","type":9,"x":411.686035803172,"y":-14.775802595421261,"angle":0}],"connections":[{"fromComponentID":"component16","fromComponentPointIndex":2,"toComponentID":"component12","toComponentPointIndex":1},{"fromComponentID":"component14","fromComponentPointIndex":2,"toComponentID":"component12","toComponentPointIndex":0},{"fromComponentID":"component12","fromComponentPointIndex":3,"toComponentID":"component16","toComponentPointIndex":0},{"fromComponentID":"component12","fromComponentPointIndex":2,"toComponentID":"component14","toComponentPointIndex":1},{"fromComponentID":"component12","fromComponentPointIndex":3,"toComponentID":"component14","toComponentPointIndex":0,"connectionPoints":[{"x":-90.02346858519785,"y":-28.40462444681476}]},{"fromComponentID":"component12","fromComponentPointIndex":2,"toComponentID":"component16","toComponentPointIndex":1,"connectionPoints":[{"x":-88.83230806584463,"y":7.806655341523238}]},{"fromComponentID":"component37","fromComponentPointIndex":2,"toComponentID":"component41","toComponentPointIndex":3,"connectionPoints":[{"x":122.60164341160497,"y":-89.99232548567866}]},{"fromComponentID":"component37","fromComponentPointIndex":3,"toComponentID":"component41","toComponentPointIndex":2,"connectionPoints":[{"x":156.73335772930113,"y":-85.27198201621009}]},{"fromComponentID":"component41","fromComponentPointIndex":0,"toComponentID":"component47","toComponentPointIndex":2},{"fromComponentID":"component37","fromComponentPointIndex":4,"toComponentID":"component47","toComponentPointIndex":3,"connectionPoints":[{"x":194.8592088288559,"y":-66.39060813833561}]},{"fromComponentID":"component47","fromComponentPointIndex":0,"toComponentID":"component37","toComponentPointIndex":0,"connectionPoints":[{"x":422.16190205096063,"y":-147.72575715071824}]},{"fromComponentID":"component41","fromComponentPointIndex":1,"toComponentID":"component51","toComponentPointIndex":1},{"fromComponentID":"component47","fromComponentPointIndex":1,"toComponentID":"component51","toComponentPointIndex":0},{"fromComponentID":"component51","fromComponentPointIndex":2,"toComponentID":"component37","toComponentPointIndex":1,"connectionPoints":[{"x":477.3536103093636,"y":-118.67748964629557}]}]}`

**Expected behavior**
The ability to place the IC.

**Screenshots**
![image](https://user-images.githubusercontent.com/74193405/201495684-de7354c5-269a-450e-a8c8-83c0a94d95c3.png)

**Desktop**

- OS: Windows
- Browser: Chrome
- Version: Wish I knew

**Comment by UnsignedArduino** [comment]
Fixed in staging.
