### ISSUE TITLE
IC duplication bug

### ISSUE THREAD

**Issue by Bobingstern** [UnsignedArduino/LogicalSimulator#187]
ICs seem to duplicate whenever there is a new import or undo is pressed. I assume that this is a problem with the export code as it does not check for the current ICs and just adds them regardless

**Comment by UnsignedArduino** [comment]
I think this is caused by the fact that the ICs will link to an existing IC definition, but the IC definition that gets imported still gets plopped in anyways without checking. Easiest would be to not create the IC definition, but it may cause consistency issues.

**Comment by UnsignedArduino** [comment]
@Bobingstern I am unable to reproduce this, please provide one.

**Comment by Bobingstern** [comment]
Create an IC definition. Place some random components and CTRL-Z. ICs should duplicate in the IC menu

**Comment by UnsignedArduino** [comment]
Ohhhhh...yea I see it. 

There is still only one physical IC definition in the circuit, which I was looking. I did not think to look in that IC menu.
