### ISSUE TITLE
Loading an example in a new tab should not override the local storage of your current project

### ISSUE THREAD

**Issue by Bobingstern** [UnsignedArduino/LogicalSimulator#193]

**Comment by UnsignedArduino** [comment]
@Bobingstern what if the user modifies the example, do we then save it? It is very easy to disable saving (with a URL parameter) but I'm unsure of how to communicate this to the user.

**Comment by Bobingstern** [comment]
There should be a popup saying "Do you want to overrite your current porject" etc when you try to modify
