### ISSUE TITLE
Hold key to stop connections from letting go

### ISSUE THREAD

**Issue by Bobingstern** [UnsignedArduino/LogicalSimulator#198]
I am noticing when building larger circuits that it becomes a pain to move the mouse forward and backwards to connect one thing to another over a long distance. It would be nice to have a hotkey that when an output connection is selected and the hotkey is held, all subsequent clicks on other input connection will instantly create a new connection without the need of selecting the output connection over and over until the hotkey is released

**Comment by UnsignedArduino** [comment]
Currently, you can click an output connection point, and click another input connection point to connect them - you do not have to drag. (This is so you can do it on mobile) Maybe, when you are holding shift and you click an output connection point or let go from dragging, it doesn't "let go."

**Comment by UnsignedArduino** [comment]
Fixed in staging.
