### ISSUE TITLE
Have option NOT to override the current project when importing a save

### ISSUE THREAD

**Issue by Bobingstern** [UnsignedArduino/LogicalSimulator#205]
This could be used to import so called "utility" circuits like half-adder ICs etc

**Comment by UnsignedArduino** [comment]
Currently, you can copy and paste IC definitions, but maybe a checkbox in the import dialog that says "Do not overwrite current project (useful for importing IC definitions)" would be good.

**Comment by UnsignedArduino** [comment]
Fixed in staging.
