### ISSUE TITLE
Allow user to see a generated truth table of an IC

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/LogicalSimulator#231]
We can first implement this (which will be easier) then we can finish https://github.com/UnsignedArduino/LogicalSimulator/issues/206.

**Comment by Bobingstern** [comment]
This is good as many online tutorials and such use truth tables and circuit diagrams so the comparison could be useful for validation of a circuit

**Comment by UnsignedArduino** [comment]
Fixed in staging.
