### ISSUE TITLE
ICs

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/LogicalSimulator#41]

**Comment by UnsignedArduino** [comment]
Pinging @Bobingstern for reference. 

So I think we can have a special button on the toolbar which opens a dialog for creating, modifying, using, and deleting ICs. 

The dialog will look something like this:

# Integrated circuits
- `Half adder`: `Edit integrated circuit` `Edit pin placements` `Export` `Delete`
- `Full adder`: `Edit integrated circuit` `Edit pin placements` `Export` `Delete`

`Create an integrated circuit` `Import an integrated circuit`

Whenever you create an IC, we will ask for the name and the number of inputs and outputs. (Specify that the number of I/O cannot be changed later) Then we clear the canvas and place down special components which represent the inputs and outputs. (which cannot be deleted or cloned) After the user clicks done, they will have created the new IC and it will get added to the list.

Whenever you edit an IC, we will clear the canvas and import the IC. They can change everything except the IC I/O components. After they click done we go through every IC, delete all the components within each IC and replace them with the new components, and reconnect them to the IC pins.

Whenever you are creating or editing an IC, the only components available are the true and false constants, clocks, all logic gates, and the note. You can also use other ICs except for the one you are editing. 

Whenever you delete an IC, you get a warning, with the number of ICs that are using that circuit. Once deleted, we delete all the ICs and the internal components. 

The special IC I/O components can have a short name assigned to them which will be displayed on the IC. These cannot be deleted. 

You can click on the IC title in the dialog to switch it to an input so you can modify it. 

Within the edit pin placements dialog, you can specify the number of pins on the top, bottom, left, and right. (It obviously must add up to the total number of pins) There will be a dropdown for each pin that will say something like `Top 1` (first spot on the left) or `Left 3` (third spot down on the left side) or `Bottom 5`. (fifth one from the left on the bottom) Options marked with stars have not been used. Selecting a spot that is used will swap them. 

This is going to take quite a while.

**Comment by Bobingstern** [comment]
This checks off all the things I had in mind, nice!

**Comment by UnsignedArduino** [comment]
Fixed in staging.
