### ISSUE TITLE
Able to drag out points of a connection to make nicer looking wires

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/LogicalSimulator#86]
Like how logic.ly does it.

**Comment by Bobingstern** [comment]
Make each wire have different otions to curve it. The default will be bezier from its midpoint and the next sub connection. The next would be a multi anchored bezier using the sub connections as anchors and the third would be just a staright line from each sub connections. This would add veritality in making a circuit look presentable and supports schematic images layout.

**Comment by Bobingstern** [comment]
The curvature could also be determined by how close the x and y of the subconnections are to the previous connection. If the Xs are close, snap them together to form a straight line. Same thing with the Ys.

**Comment by UnsignedArduino** [comment]
@Bobingstern we will probably end up doing that at some point: https://github.com/UnsignedArduino/LogicalSimulator/issues/116 (probably as a "ComponentAttribute")

**Comment by UnsignedArduino** [comment]
Fixed in staging.
